package calc;

import java.util.StringTokenizer;

/**
 *
 * @author Ahmed El-Torky
 */
public class CalcFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcFrame
     */
    public CalcFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonNine = new javax.swing.JButton();
        ButtonEight = new javax.swing.JButton();
        ButtonSix = new javax.swing.JButton();
        ButtonOne = new javax.swing.JButton();
        ButtonFive = new javax.swing.JButton();
        ButtonTwo = new javax.swing.JButton();
        ButtonFour = new javax.swing.JButton();
        ButtonDot = new javax.swing.JButton();
        ButtonZero = new javax.swing.JButton();
        ButtonThree = new javax.swing.JButton();
        ButtonSeven = new javax.swing.JButton();
        ButtonMul = new javax.swing.JButton();
        ButtonDiv = new javax.swing.JButton();
        ButtonSub = new javax.swing.JButton();
        ButtonAns = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();
        ButtonAdd1 = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        LabelScreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator 1.0 Beta");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        ButtonNine.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonNine.setText("9");
        ButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNineActionPerformed(evt);
            }
        });

        ButtonEight.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonEight.setText("8");
        ButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEightActionPerformed(evt);
            }
        });

        ButtonSix.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonSix.setText("6");
        ButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSixActionPerformed(evt);
            }
        });

        ButtonOne.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonOne.setText("1");
        ButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOneActionPerformed(evt);
            }
        });

        ButtonFive.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonFive.setText("5");
        ButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFiveActionPerformed(evt);
            }
        });

        ButtonTwo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonTwo.setText("2");
        ButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTwoActionPerformed(evt);
            }
        });

        ButtonFour.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonFour.setText("4");
        ButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFourActionPerformed(evt);
            }
        });

        ButtonDot.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonDot.setText(".");
        ButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDotActionPerformed(evt);
            }
        });

        ButtonZero.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonZero.setText("0");
        ButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonZeroActionPerformed(evt);
            }
        });

        ButtonThree.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonThree.setText("3");
        ButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThreeActionPerformed(evt);
            }
        });

        ButtonSeven.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonSeven.setText("7");
        ButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSevenActionPerformed(evt);
            }
        });

        ButtonMul.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonMul.setText("*");
        ButtonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMulActionPerformed(evt);
            }
        });

        ButtonDiv.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonDiv.setText("/");
        ButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivActionPerformed(evt);
            }
        });

        ButtonSub.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonSub.setText("-");
        ButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubActionPerformed(evt);
            }
        });

        ButtonAns.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonAns.setText("ans");
        ButtonAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnsActionPerformed(evt);
            }
        });

        ButtonEqual.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonEqual.setText("=");
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });

        ButtonAdd1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonAdd1.setText("+");
        ButtonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdd1ActionPerformed(evt);
            }
        });

        ButtonClear.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonClear.setText("CLR");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        LabelScreen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonOne)
                                    .addComponent(ButtonFour))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonFive)
                                    .addComponent(ButtonTwo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonSeven)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonEight))
                            .addComponent(ButtonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ButtonEqual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAns, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear))
                .addGap(15, 15, 15))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonAdd1, ButtonAns, ButtonClear, ButtonDiv, ButtonMul, ButtonSub});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonDot, ButtonEight, ButtonFive, ButtonFour, ButtonNine, ButtonOne, ButtonSeven, ButtonSix, ButtonThree, ButtonTwo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(ButtonAns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonAdd1, ButtonAns, ButtonClear, ButtonDiv, ButtonMul, ButtonSub, LabelScreen});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonDot, ButtonEight, ButtonFive, ButtonFour, ButtonNine, ButtonOne, ButtonSeven, ButtonSix, ButtonThree, ButtonTwo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String ans = "0";
    StringTokenizer st;
    double sum = 0;
    char op = 'E';
    int finish = 0;
    char dot = 'E';
    private void ButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTwoActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonTwoActionPerformed

    private void ButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNineActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonNineActionPerformed

    private void ButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThreeActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonThreeActionPerformed

    private void ButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOneActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + "1");
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonOneActionPerformed

    private void ButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFiveActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonFiveActionPerformed

    private void ButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSevenActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + "7");
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonSevenActionPerformed

    private void ButtonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEightActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonEightActionPerformed

    private void ButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFourActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonFourActionPerformed

    private void ButtonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSixActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonSixActionPerformed

    private void ButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonZeroActionPerformed
        if (finish == 0 || op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
        } else {
            LabelScreen.setText(evt.getActionCommand());
            finish = 0;
        }
    }//GEN-LAST:event_ButtonZeroActionPerformed

    private void ButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDotActionPerformed
        if (dot == 'E') {
            if (finish == 0 || op != 'E') {
                if (LabelScreen.getText() == "") {
                    LabelScreen.setText("0.");
                    dot = '.';
                } else {
                    LabelScreen.setText(LabelScreen.getText() + ".");
                    dot = '.';
                }
            } else {
                LabelScreen.setText("0.");
                finish = 0;
                dot = '.';
            }
        }
    }//GEN-LAST:event_ButtonDotActionPerformed

    private void ButtonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMulActionPerformed
        if (LabelScreen.getText() != "") {
            if (op == 'E') {
                op = '*';
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
            } else {
                this.ButtonEqualActionPerformed(evt);
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
                op = '*';
            }
            dot = 'E';
        }
    }//GEN-LAST:event_ButtonMulActionPerformed

    private void ButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivActionPerformed
        if (LabelScreen.getText() != "") {
            if (op == 'E') {
                op = '/';
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
            } else {
                this.ButtonEqualActionPerformed(evt);
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
                op = '/';
            }
            dot = 'E';
        }
    }//GEN-LAST:event_ButtonDivActionPerformed

    private void ButtonAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnsActionPerformed
        if (ans != "0" && op != 'E') {
            LabelScreen.setText(LabelScreen.getText() + ans);
        } else {
            LabelScreen.setText(ans);
            finish = 1;
        }
    }//GEN-LAST:event_ButtonAnsActionPerformed

    private void ButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubActionPerformed
        if (LabelScreen.getText() != "") {
            if (op == 'E') {
                op = '-';
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
            } else {
                this.ButtonEqualActionPerformed(evt);
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
                op = '-';
            }
            dot = 'E';
        }
    }//GEN-LAST:event_ButtonSubActionPerformed

    private void ButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdd1ActionPerformed
        if (LabelScreen.getText() != "") {
            if (op == 'E') {
                op = '+';
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
            } else {
                this.ButtonEqualActionPerformed(evt);
                LabelScreen.setText(LabelScreen.getText() + evt.getActionCommand());
                op = '+';
            }
            dot = 'E';
        }
    }//GEN-LAST:event_ButtonAdd1ActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        this.StringTokenizer(LabelScreen.getText(), "+-*/");
        if (st.countTokens() < 2) {
            LabelScreen.setText(LabelScreen.getText());
        } else {
            switch (op) {
                case '+':
                    sum = Double.parseDouble(st.nextToken()) + Double.parseDouble(st.nextToken());
                    ans = sum + "";
                    sum = 0;
                    op = 'E';
                    finish = 1;
                    dot = 'E';
                    LabelScreen.setText(ans);
                    break;
                case '-':
                    sum = Double.parseDouble(st.nextToken()) - Double.parseDouble(st.nextToken());
                    ans = sum + "";
                    sum = 0;
                    op = 'E';
                    finish = 1;
                    dot = 'E';
                    LabelScreen.setText(ans);
                    break;
                case '*':
                    sum = Double.parseDouble(st.nextToken()) * Double.parseDouble(st.nextToken());
                    ans = sum + "";
                    sum = 0;
                    op = 'E';
                    finish = 1;
                    dot = 'E';
                    LabelScreen.setText(ans);
                    break;
                case '/':
                    sum = Double.parseDouble(st.nextToken()) / Double.parseDouble(st.nextToken());
                    ans = sum + "";
                    sum = 0;
                    op = 'E';
                    finish = 1;
                    dot = 'E';
                    LabelScreen.setText(ans);
                    break;
            }
        }
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        LabelScreen.setText("");
        sum = 0;
        dot = 'E';
        op = 'E';
    }//GEN-LAST:event_ButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd1;
    private javax.swing.JButton ButtonAns;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDiv;
    private javax.swing.JButton ButtonDot;
    private javax.swing.JButton ButtonEight;
    private javax.swing.JButton ButtonEqual;
    private javax.swing.JButton ButtonFive;
    private javax.swing.JButton ButtonFour;
    private javax.swing.JButton ButtonMul;
    private javax.swing.JButton ButtonNine;
    private javax.swing.JButton ButtonOne;
    private javax.swing.JButton ButtonSeven;
    private javax.swing.JButton ButtonSix;
    private javax.swing.JButton ButtonSub;
    private javax.swing.JButton ButtonThree;
    private javax.swing.JButton ButtonTwo;
    private javax.swing.JButton ButtonZero;
    private javax.swing.JLabel LabelScreen;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private StringTokenizer StringTokenizer(String text, String string) {
        return st = new StringTokenizer(text, string);
    }
}
